name: flock_map_app
description: Simple OSM camera‑mapping client
publish_to: "none"
version: 0.5.0

environment:
  sdk: ">=3.5.0 <4.0.0"   # oauth2_client 4.x needs Dart 3.5+

dependencies:
  flutter:
    sdk: flutter

  # UI & Map
  provider: ^6.1.2
  flutter_map: ^8.2.1
  # (removed: using built-in Scalebar from flutter_map >= v6)
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  http: ^1.2.1

  # Auth, storage, prefs
  oauth2_client: ^4.2.0
  flutter_web_auth_2: 5.0.0-alpha.3
  flutter_secure_storage: 10.0.0-beta.4

  # Persistence
  shared_preferences: ^2.2.2
  uuid: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/info.txt
    - assets/transparent_1x1.png
    - assets/black_1x1.png
